services:
  backend:
    build: ./backend
    container_name: tt-backend
    volumes:
      - ./backend/timetable.db:/app/timetable.db
    environment:
      - DATABASE_URL=sqlite:///./timetable.db
    restart: always

  frontend:
    build: ./frontend
    container_name: tt-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
